### ISSUE TITLE
7-word offline solution

### ISSUE THREAD

**Issue by Armavica** [alexandres/magicwordschallenge#1]
```
echo CLANG FATTY ODDER RUMBA SKILL VERGE WHOOP | ./check
```
All of these words appear in the `words.txt` file (so they are all possible solutions).

**Comment by alexandres** [comment]
Awesome! Thank you Armavica. I've added your solution to the the README: https://github.com/alexandres/magicwordschallenge/commit/43dd44cd8c32b8aa933d4e02a97c90982512c239

Curious to know how you found the solution.

**Comment by Armavica** [comment]
I found it with simulated annealing. I am also getting frustratingly close to a 6-word solution (only 1 collision!)…

**Comment by alexandres** [comment]
Nice! I was leaning towards there being no 5 word solution but if there's a 6 word solution all bets are off and it might just exist.
